title: Bud Parr
baseURL: "https://www.budparr.com"
languageCode: en-us
mainSections: 
  - article
  - post
  
#themesDir: components
theme: github.com/budparr/hugo-theme-novela
MetaDataFormat: yaml
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 12
googleAnalytics: UA-30899180-2
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  description: "Web Technologist, Open Source Contributor, Community Builder, Entrepeneur"
  faceboook: ""
  twitter: "http://twitter.com/budparr"
  instagram: ""
  youtube: ""
  background_color_class: bg-black
  featured_image: /images/gohugo-default-sample-hero-image.jpg
  fathom_id: CIKSICWQ
taxonomies:
  tag: authors
module:
  imports:
    - path: github.com/theNewDynamic/tnd-assets-js/fathom-analytics
    